### ISSUE TITLE
cli安装方式mpShare路径错误问题

### ISSUE THREAD

**Issue by gbgba159** [climblee/uv-ui#12]
平台: 微信小程序
版本: "@climblee/uv-ui": "^1.1.12"
问题: `运行到微信小程序平台时报错"../../libs/mixin/mpShare.js"不存在,检查为@climblee/uv-ui/index.js中mpShare引用路径错误

`yarn run v1.22.19
warning package.json: No license field
$ cross-env UNI_ENV=dev uni -p mp-weixin
请注意运行模式下，因日志输出、sourcemap 以及未压缩源码等原因，性能和包体积，均不及发行模式。若
要正式发布，请点击发行菜单或使用 cli 发布命令进行发布
正在编译中...
Could not resolve "../../libs/mixin/mpShare.js" from "node_modules/@climblee/uv-ui/index.js"
at ../node_modules/@climblee/uv-ui/index.js:1:0`

- @climblee/uv-ui/index.js
`// 小程序特有的mixin
import mpMixin from './libs/mixin/mpMixin.js'
// #ifdef MP
import mpShare from '../../libs/mixin/mpShare.js'
// #endif`

**Comment by climblee** [comment]
已经修改，使用npm update更新一下就好啦

**Comment by gbgba159** [comment]
感谢大佬分享
