### ISSUE TITLE
uv-calendar 微信小程序 日期和周对应不上

### ISSUE THREAD

**Issue by H-hejin** [climblee/uv-ui#134]
![Uploading Snipaste_2024-09-11_16-26-39.png…]()

**Comment by H-hejin** [comment]
问题已解决：
getWrapperWidth() {
				// #ifdef APP-NVUE
				dom.getComponentRect(this.$refs['uv-calendar-month-wrapper'], res => {
					this.width = res.size.width
				})
				// #endif
				// #ifndef APP-NVUE
				this.$uvGetRect('.uv-calendar-month-wrapper').then(size => {
					this.width = size.width
					console.log(size, 'size')
				})
				// #endif
			},
看了一下源码；这段代码在微信小程序上渲染机制不同，导致获取的宽度为0，导致上面动态计算出现了问题也就是这一段代码：
dayStyle(index1, index2, item) {
				return (index1, index2, item) => {
					const style = {}
					let week = item.week
					// 不进行四舍五入的形式保留2位小数
					// const dayWidth = Number(parseFloat(this.width / 7).toFixed(3).slice(0, -1))
					const dayWidth = Number((this.width / 7).toFixed(2));
					// console.log(this.width, 'this.width')
					// 得出每个日期的宽度
					// #ifdef APP-NVUE
					style.width = this.$uv.addUnit(dayWidth)
					// #endif
					style.height = this.$uv.addUnit(this.rowHeight)
					if (index2 === 0) {
						// 获取当前为星期几，如果为0，则为星期天，减一为每月第一天时，需要向左偏移的item个数
						week = (week === 0 ? 7 : week) - 1
						style.marginLeft = this.$uv.addUnit(week * dayWidth)
					}
					if (this.mode === 'range') {
						// 之所以需要这么写，是因为DCloud公司的iOS客户端的开发者能力有限导致的bug
						style.paddingLeft = 0
						style.paddingRight = 0
						style.paddingBottom = 0
						style.paddingTop = 0
					}
					return style
				}
			},
解决方式很简单：在uv-calendar.vue里面把uvMonth组件加一个v-if 在opne的时候设置为true就解决了

**Comment by H-hejin** [comment]
这个问题真是让我头大，组件都不进行测试的吗？？？

**Comment by hanyucd** [comment]
@H-hejin 哥，这日期不对应周的问题，确实在微信小程序存在 (**已解决**)

你说的这句话： “解决方式很简单：在uv-calendar.vue里面把uvMonth组件加一个v-if 在opne的时候设置为true就解决了”。

我就是在 node_modules 中的 uv-calendar.vue 里面：

模板代码：
<uvMonth
  **// 新添加**
   v-if="isShowUVMonth"
   ...
  />

js代码：
open() {
    this.setMonth()
    this.$refs.calendarPopup.open();
    **// 新添加**
   this.isShowUVMonth = true;
},


**备注：这个 isShowUVMonth 是添加的一个响应式字段**

**Comment by H-hejin** [comment]
1. @hanyucd 我用的uni_modules形式，给uvMonth加上v-if，uv-calendar源码里面 
2.  open() {
				this.monthShow = true
				this.$nextTick(() => {
					this.setMonth()
					this.$refs.calendarPopup.open();
				})
			},
3. confirm() {
				if (!this.buttonDisabled) {
					this.$emit('confirm', this.selected)
				}
				if (this.closeOnClickConfirm) {
					this.monthShow = false
					this.$refs.calendarPopup.close();
				}
			},
4. <uvMonth v-if="monthShow" :color="color" :rowHeight="rowHeight" :showMark="showMark" :months="months" :mode="mode"
					:maxCount="maxCount" :startText="startText" :endText="endText" :defaultDate="defaultDate"
					:minDate="innerMinDate" :maxDate="innerMaxDate" :maxMonth="monthNum" :readonly="readonly"
					:maxRange="maxRange" :rangePrompt="rangePrompt" :showRangePrompt="showRangePrompt"
					:allowSameDay="allowSameDay" ref="month" @monthSelected="monthSelected"
					@updateMonthTop="updateMonthTop" @change="changeDay"></uvMonth>
5. data() {
			return {
				// 处理微信小程序日期显示问题
				monthShow: false,
				// 需要显示的月份的数组
				months: [],
				// 在月份滚动区域中，当前视图中月份的index索引
				monthIndex: 0,
				// 月份滚动区域的高度
				listHeight: 0,
				// month组件中选择的日期数组
				selected: [],
				scrollIntoView: '',
				scrollTop: 0,
				// 过滤处理方法
				innerFormatter: (value) => value
			}
		},

**Comment by hanyucd** [comment]
@H-hejin 嗯嗯，好的。感觉这个方法 **治表不治根**，这个 bug 估计还是得官方去解决，😄

**Comment by H-hejin** [comment]
@hanyucd 是的，这个问题官方不解决，就得改源码；没有什么其它好方法

**Comment by Champion-Chen** [comment]
今天也遇到这问题了，上面的图片挂掉了，也不知道我们说的是不是一回事。

修改也简单的，就是把每月第1日“挤”到正确列。看到的人希望有所帮助吧。

uni_modules -> month.vue

模板中搜索第二行的内容，在前面添加第一行：
				`<view  class="uv-calendar-month__days__day" v-for="(item1, index1) in getDayOffest(item.date[0])" :key="index1"></view>	`			
`<view class="uv-calendar-month__days__day" v-for="(item1, index1) in item.date" :key="index1"....`

方法添加：
`getDayOffest(firstDate){
	var offset = firstDate.week?firstDate.week - 1 : 6;
	return new Array(offset);
},`
