### ISSUE TITLE
uv-calendars 组件，mode=range 模式 ，无法选择同一天

### ISSUE THREAD

**Issue by Cassie-Yu** [climblee/uv-ui#14]

**Comment by climblee** [comment]
亲爱的  就是这样设计的  不能选择同一天的

**Comment by shijunti19** [comment]
@climblee 这肯定不对啊，第一个选择的00:00:00第二个选的223:59:59那你选当天就实现不了，你这种错误逻辑

**Comment by Cassie-Yu** [comment]
> 亲爱的 就是这样设计的 不能选择同一天的

最新的uView 2.0版本有加一个参数allowSameDay ，可以满足range模式下选择同一天呢

ps：其实我们的使用场景是日期范围的搜索条件，所以应该是要可以选择当天  (●＾o＾●)(★＞U＜★)

**Comment by shijunti19** [comment]
@Lee1124 可不可以加参数，然后当天他就是一个点

**Comment by climblee** [comment]
已经增加allowSameDay 参数，更新下直接用，文档后面更新
