### ISSUE TITLE
picker动态赋值后，滚动第二列，返回的数据有问题的，应该是1,2

### ISSUE THREAD

**Issue by shijunti19** [climblee/uv-ui#15]
![image](https://github.com/climblee/uv-ui/assets/5392211/125b93f8-8456-4a46-b622-e51c3fe8d53e)
picker动态赋值后，滚动第二列，返回的数据有问题的，应该是1,2

你查下吧，你肯定漏赋值了什么
```
  setTimeout(function () {
    pickerDefaultIndex.value = [1, 2];
    // pickerRef.value.setIndexs([1, 2], true);
  }, 500);
```
而且我必须用定时器才可以实现赋值，这也是有问题的，这个延迟应该是在内部解决的

**Comment by climblee** [comment]
1. 你说的第一个问题，看你截图是没有毛病的。这个三级联动的示例我已经出了，就这两天更新文档。
2. 你说的给延时，实际上是组件还没渲染完成，所以你可以在onReady周期函数或者给延时才能去调取，是没问题哈，vue基础嘛。

**Comment by shijunti19** [comment]
@climblee 我说呢怎么会出问题
![image](https://github.com/climblee/uv-ui/assets/5392211/b5b41d03-daf9-4bc9-9772-8eacbc3f76dc)
文档里有true：this.$refs.picker.setIndexs([1],true)
你的例子没有的
没有的才是正常的
