### ISSUE TITLE
uv-tabs 使用问题

### ISSUE THREAD

**Issue by FangPro** [climblee/uv-ui#3]
平台：钉钉小程序
组件：uv-tabs
错误提示：
      message: "Cannot read properties of undefined (reading 'rect')"
stack: "TypeError: Cannot read properties of undefined (reading 'rect')\n at s.setScrollLeft (http://127.0.0.1:61786/index.worker.js?version=8b5ae8ca&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&appId=5000000004854676&query=corpId%3Ddingbc51f1e7f1f6deeb&chInfo=ch_scan&referrerInfo=%7B%7D&ddAppType=org&ap_framework_sceneId=1011:196:4841)\n at http://127.0.0.1:61786/index.worker.js?version=8b5ae8ca&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&appId=5000000004854676&query=corpId%3Ddingbc51f1e7f1f6deeb&chInfo=ch_scan&referrerInfo=%7B%7D&ddAppType=org&ap_framework_sceneId=1011:196:5286"

**Comment by uLeePan** [comment]
这个问题你可以自己尝试改下，钉钉小程序我们不做支持哈

**Comment by FangPro** [comment]
改好了，我把watch里对当前下标值（innerCurrent）重新赋值的代码注释了，watch里的current方法，初始化时new值和old值还是0（Number类型），点击tab后，new值和old值就变成了带有rect信息的对象了，如果继续给当前下标值（innerCurrent）重新赋值就直接undifined了，至于为什么这样，我还不是很清楚。总之，你们的组件很好用，希望你们继续坚持，谢谢。
