### ISSUE TITLE
calendars 有BUG，部分日期无法选中

### ISSUE THREAD

**Issue by kkqy** [climblee/uv-ui#37]
比如 2023年7月30日和31日，7月最后一天只能到29日，必须翻到8月才能看到7月31日，但是再8月那一页里7月的日期是灰色，也无法选中。
<img width="301" alt="屏幕截图 2023-11-18 025855" src="https://github.com/climblee/uv-ui/assets/3955922/2f83b6a7-574c-4171-9c49-35a391212e11">

**Comment by climblee** [comment]
1. 你这个页面有问题，下面没显示完整
2. 你检查下是不是套在其他组件里面了
3. 你检查下是不是样式被覆盖了

**Comment by kkqy** [comment]
> 1. 你这个页面有问题，下面没显示完整
> 2. 你检查下是不是套在其他组件里面了
> 3. 你检查下是不是样式被覆盖了

我看了 确实被tabbar挡住了（这个tabbar是uniapp的tabbar，而非自定义组件），但是我怎么调整呢？
我看API里面没有提供设置下边距的。

**Comment by climblee** [comment]
你是H5端是吧，H5端且有tabbar就需要你自己用样式穿透一下

**Comment by kkqy** [comment]
> 你是H5端是吧，H5端且有tabbar就需要你自己用样式穿透一下

好的
