### ISSUE TITLE
ActionSheet高度问题

### ISSUE THREAD

**Issue by Dongweilong121** [climblee/uv-ui#42]
使用**ActionSheet组件**,数据过多的时候会将组件的高度自适应至全屏,能否设置固定高度 , 数据可以在组件内滑动加载

**Comment by climblee** [comment]
该组件不适合数据过多的场景，数据过多你就要使用uv-picker或者uv-popup组件进行自定义内容啦

**Comment by Dongweilong121** [comment]
好的 谢谢您的解答
