### ISSUE TITLE
是否有支持暗黑模式的计划

### ISSUE THREAD

**Issue by seepine** [climblee/uv-ui#43]
目前虽然通过自定义css变量和自定义组件props，达到能简单支持，但好多地方在css写死的值，或者没有暴露的，就导致如果不改源码很难应用到实际项目中

![image](https://github.com/climblee/uv-ui/assets/93666053/ed7a8a96-9cbd-49a8-bd1a-fa73dece6645)
![image](https://github.com/climblee/uv-ui/assets/93666053/adb26b5b-c080-4f0d-8d7f-9881a2b544ca)

![image](https://github.com/climblee/uv-ui/assets/93666053/91b4c6aa-b3d9-4391-af3f-9697458b4e74)
![image](https://github.com/climblee/uv-ui/assets/93666053/83af4694-d4be-40de-8136-c3d2efc44e25)

**Comment by climblee** [comment]
这套组件不能支持黑暗主题哈，只能修改主题色和你手动设置
