### ISSUE TITLE
真机调试无法显示组件

### ISSUE THREAD

**Issue by jiewenhuang** [climblee/uv-ui#76]
<img width="478" alt="image" src="https://github.com/climblee/uv-ui/assets/68629578/59a52fe6-5c76-416b-823c-35fdabb57bca">
<img width="661" alt="image" src="https://github.com/climblee/uv-ui/assets/68629578/780b8a2e-b3b6-4437-b7f7-e090ee09798d">

![bdf2b16ffb3ca2e65919db7a6d43d497](https://github.com/climblee/uv-ui/assets/68629578/3309832c-7837-41e1-b4e9-db7d45d1ef96)

在开发工具里是能正常显示的，但是真机调试组件直接不见了。机型14pro

**Comment by Lee1124** [comment]
用运行，别真机预览
