### ISSUE TITLE
开启skyline 引擎渲染后 大部分组件失效

### ISSUE THREAD

**Issue by zcjunblog** [climblee/uv-ui#85]
1. webview引擎渲染下正常使用
2. 开发工具开启skyline引擎渲染 uv-popup, uv-no-network, uv-datetime-picker测试失效 其余未测

开启skyline引擎渲染步骤:
1.在manifest.json添加
`   "lazyCodeLoading": "requiredComponents",
        "renderer": "skyline",
        "componentFramework": "glass-easel",
        "rendererOptions": {
            "skyline": {
                "defaultDisplayBlock": true
            }
        },`

2.pages.json对应页面添加
`        {
            "path": "pages/index/index",
            "style": {
                "navigationStyle": "custom",
                "disableScroll": true
            }
        },`
3.开发工具勾选skyline引擎渲染

**Comment by Lee1124** [comment]
不支持skyline
