### ISSUE TITLE
uv-datetime-picker组件的时间(time)模式中能否增加列表的循环滚动

### ISSUE THREAD

**Issue by wjw020206** [climblee/uv-ui#88]
能否支持选择时间时可以接着往下滑动而不用往回滑动的功能，例如：01滑动到59后再往后滑接着从01开始
<img width="320" alt="image" src="https://github.com/umicro/uView2.0/assets/59106659/1b099ad8-a9ee-42fd-ba72-6e9845547d55">

**Comment by Lee1124** [comment]
不支持

**Comment by wjw020206** [comment]
> 不支持

感谢回复，那请问有什么方案可以实现这个效果？后续可以支持吗？

**Comment by Lee1124** [comment]
不会支持呢，没必要那么较真啦！哪个产品说的一定需要这个功能，那就把产品炒了

**Comment by wjw020206** [comment]
> 不会支持呢，没必要那么较真啦！哪个产品说的一定需要这个功能，那就把产品炒了

甲方要求的

**Comment by Lee1124** [comment]
如果这种功能不能商量的话  没必要和这种甲方合作
