### ISSUE TITLE
#uv-switch async-change无效

### ISSUE THREAD

**Issue by Lyansun** [climblee/uv-ui#9]
如题描述，使用过程中uv-switch的async-change不生效，加上该属性后UI也会立刻更新（v-model值无更新，这是正确的） 
uniapp，vue3

**Comment by Lee1124** [comment]
把你代码贴出来呢？v-model值无更新，又是正确的？这里只能用v-model

**Comment by Lyansun** [comment]
`<template>
	<view>
		{{value}}
		<uv-switch v-model="value" asyncChange @change="asyncChange"></uv-switch>
	</view>
</template>

<script lang="ts">
	import { defineComponent, ref } from "vue";
	export default defineComponent({
		setup() {
			const value = ref(false);
			const asyncChange = (e) => {
				uni.showModal({
					content: e ? '确定要打开吗' : '确定要关闭吗',
					success: (res) => {
						if (res.confirm) {
							value.value = e;
						}
					}
				})
			}
			return {
				value,
				asyncChange
			}
		}
	})
</script>
`
根据文档指引，开启asyncChange应先触发@change，v-model双向绑定应失效，目前这点验证正确。问题出在开启asyncChange后并没有先阻止Switch的UI变化，只要点击了Switch都会进行开和关的UI效果，这点跟文档演示效果不一致。

**Comment by climblee** [comment]
我明白你说的了，之前版本确实有这个问题，在8月23号，你把uv-switch版本更新到1.0.4

**Comment by climblee** [comment]
如果还有问题就加Q群：549833913

**Comment by Lyansun** [comment]
验证已解决。

**Comment by climblee** [comment]
OK
